function [test, validate, train] = get_rand_abgo_imds(fileName) % fileName = path abgo subfolders

% Replicable Randomized Data 

anthro_DS = imageDatastore(fileName+"/anthro","LabelSource","foldernames"); 
bio_DS = imageDatastore(fileName+"/bio","LabelSource","foldernames");
geo_DS = imageDatastore(fileName+"/geo","LabelSource","foldernames");
other_DS = imageDatastore(fileName+"/other","LabelSource","foldernames");

% Seed Random Number Generator
% Set seeded rng at 10. Change value to test other randomized data sets.
rng(10);

% Test Data: 50 from each category

test =   imageDatastore(union(...
                        union(...
                        rand_subset(anthro_DS,50,randperm(size(anthro_DS.Labels,1),50)),...
                        rand_subset(bio_DS,50,randperm(size(bio_DS.Labels,1),50))...
                        ),...
                        union(...
                        rand_subset(geo_DS,50,randperm(size(geo_DS.Labels,1),50)),...
                        rand_subset(other_DS,50,randperm(size(other_DS.Labels,1),50))...
                        )...
                        ),...
                        "LabelSource","foldernames"...
                        );
% Validation Data: 200 from anthro, bio and geo. 50 from other
validate = imageDatastore(union(...
                        union(...
                        rand_subset(anthro_DS, 200, randperm(size(anthro_DS.Labels,1),200)),...
                        rand_subset(bio_DS,200,randperm(size(bio_DS.Labels,1),200))...
                        ),...
                        union(...
                        rand_subset(geo_DS,200,randperm(size(geo_DS.Labels,1),200)),...
                        rand_subset(other_DS,50,randperm(size(other_DS.Labels,1),50))...
                        )...
                        ),...
                        "LabelSource","foldernames"...
                       );
% Train Data: All remaining images from all categories
train =  imageDatastore(union(...
                        union(anthro_DS.Files,bio_DS.Files),...
                        union(geo_DS.Files,other_DS.Files)...
                        ),...
                        "LabelSource","foldernames"...
                        );
%Function to create a replicable random permutation of files from an existing datastore 
    function data_store = rand_subset(imds,size,perm)
        data_store = cell(size,1);
        % add files at indicies from perm into new datastore
        for i=1:size 
            data_store(i,1) = imds.Files(perm(1,i),:);
        end 
        % remove files from main datastore
        perm = perm';
        files_r = setdiff(imds.Files,imds.Files(perm,:));
        imds = imageDatastore(files_r,'LabelSource','foldernames');
    end

end

